CREATE TABLE quotes (
    id integer primary key generated by default as identity,
    customer_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone DEFAULT (CURRENT_TIMESTAMP + INTERVAL '5 minutes'),
    price integer NOT NULL,
    is_used boolean DEFAULT FALSE
);


ALTER TABLE quotes OWNER TO postgres;


CREATE TABLE quote_items (
    id integer primary key generated by default as identity,
    quote_id integer NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
    item_id integer NOT NULL REFERENCES food_places_items(id) ON DELETE CASCADE,
    quantity integer NOT NULL,
    total_price integer NOT NULL
);


ALTER TABLE quote_items OWNER TO postgres;
