--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2024-12-18 14:16:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET search_path = public, pg_catalog;

BEGIN;

DROP SCHEMA IF EXISTS topology CASCADE;
DROP SCHEMA IF EXISTS tiger CASCADE;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


CREATE FUNCTION public.update_food_places_search_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$BEGIN
  NEW.search_vector = to_tsvector('english', NEW.name || ' ' || NEW.category || ' ' || COALESCE(NEW.description, ''));
  RETURN NEW;
END;$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.users (
    id integer primary key generated by default as identity,
    first_name text NOT NULL,
    surname text NOT NULL,
    phone_number text NOT NULL,
    password text NOT NULL,
    user_type integer NOT NULL CHECK (user_type IN (1, 2, 3)),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (phone_number, user_type)
);

CREATE TABLE public.addresses (
    id integer primary key generated by default as identity,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    number_and_street text NOT NULL,
    city text NOT NULL,
    postcode text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, number_and_street, city, postcode)
);

CREATE TABLE public.drivers_statuses (
    driver_id integer PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
    status integer NOT NULL CHECK (status IN (1, 2, 3)),
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.drivers_locations (
    driver_id integer PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
    location public.geometry(Point, 4326),
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.food_places_locations (
    id integer primary key generated by default as identity,
    location public.geometry(Point, 4326) NOT NULL CHECK (
        ST_SRID(location) = 4326
    )
);

CREATE TABLE public.food_places (
    id integer primary key generated by default as identity,
    name character varying(100) NOT NULL,
    category character varying(100) NOT NULL,
    description text,
    search_vector tsvector,
    location_id integer NOT NULL REFERENCES food_places_locations(id) ON DELETE RESTRICT,
    address_id integer REFERENCES addresses(id) ON DELETE RESTRICT,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.food_places_items (
    id integer primary key generated by default as identity,
    food_place_id integer NOT NULL REFERENCES food_places(id) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    description text,
    price integer NOT NULL,  -- Price in pence (GBP)
    is_available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.carts (
    id integer primary key generated by default as identity,
    customer_id integer REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '5 minutes')
);

CREATE TABLE public.cart_pricings (
    cart_id integer primary key REFERENCES carts(id) ON DELETE CASCADE,
    service_fee integer NOT NULL,
    delivery_fee integer
);

CREATE TABLE public.cart_items (
    cart_id integer REFERENCES carts(id) ON DELETE CASCADE,
    item_id integer REFERENCES food_places_items(id) ON DELETE CASCADE,
    PRIMARY KEY (cart_id, item_id),
    quantity integer NOT NULL,
    unit_price integer NOT NULL,
    CONSTRAINT chk_cart_items_positive CHECK (quantity > 0 AND unit_price > 0)
);

CREATE TABLE public.orders (
    id integer primary key generated by default as identity,
    customer_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    food_place_id integer NOT NULL REFERENCES food_places(id) ON DELETE RESTRICT,
    delivery_address_id integer NOT NULL REFERENCES addresses(id) ON DELETE RESTRICT,
    service_fee integer NOT NULL,
    delivery_fee integer NOT NULL,
    status integer NOT NULL CHECK (status IN (0, 1, 2, 3, 4, 5, -1)),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_orders_fees_nonnegative CHECK (service_fee >= 0 AND delivery_fee >= 0)
);

CREATE TABLE public.order_items (
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    item_id integer NOT NULL REFERENCES food_places_items(id) ON DELETE RESTRICT,
    quantity integer NOT NULL,
    unit_price integer NOT NULL,
    PRIMARY KEY (order_id, item_id),
    CONSTRAINT chk_order_items_positive CHECK (quantity > 0 AND unit_price > 0)
);

CREATE TABLE public.deliveries (
    id integer primary key generated by default as identity,
    order_id integer REFERENCES orders(id) ON DELETE RESTRICT,
    driver_id integer REFERENCES users(id) ON DELETE RESTRICT,
    confirmation_code text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status integer NOT NULL CHECK (status IN (1, 2, 3, 4, 5, -1)),
    delivered_at timestamp with time zone,
    route JSONB,
    payment_amount integer
);

CREATE TABLE public.driver_location_history (
    id integer primary key generated by default as identity,
    driver_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    accuracy numeric(8, 2) NOT NULL, -- accuracy in meters from GPS device
    speed numeric(6, 2), -- speed in m/s from GPS device
    heading numeric(5, 2), -- heading in degrees (0-360) from GPS device
    timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivery_id integer REFERENCES deliveries(id) ON DELETE SET NULL
);

CREATE TABLE public.payments (
    order_id integer PRIMARY KEY REFERENCES orders(id) ON DELETE RESTRICT,
    stripe_payment_intent_id text NOT NULL,
    amount integer NOT NULL,
    status integer NOT NULL CHECK (status IN (0, 1, 2, -1, -2, -3)),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.refresh_tokens (
    user_id integer primary key REFERENCES users(id) ON DELETE CASCADE,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE INDEX idx_refresh_tokens_expires_at ON public.refresh_tokens(expires_at);

CREATE INDEX idx_search_vector ON public.food_places USING gin (search_vector) WITH (fastupdate='true');

CREATE INDEX idx_orders_customer_id ON public.orders(customer_id);
CREATE INDEX idx_orders_food_place_id ON public.orders(food_place_id);
CREATE INDEX idx_orders_delivery_address_id ON public.orders(delivery_address_id);

CREATE INDEX idx_addresses_user_id ON public.addresses(user_id);

CREATE INDEX idx_food_places_items_food_place_id ON public.food_places_items(food_place_id);

CREATE INDEX idx_deliveries_driver_id ON public.deliveries(driver_id);
CREATE INDEX idx_deliveries_order_id ON public.deliveries(order_id);

CREATE INDEX idx_driver_location_history_delivery_id ON public.driver_location_history (delivery_id);

CREATE INDEX idx_food_places_locations_geom ON public.food_places_locations USING GIST(location);

CREATE TRIGGER trg_update_search_vector BEFORE INSERT OR UPDATE OF name, category ON public.food_places FOR EACH ROW EXECUTE FUNCTION public.update_food_places_search_vector();

CREATE OR REPLACE FUNCTION set_updated_at_now()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT table_schema, table_name
        FROM information_schema.columns
        WHERE column_name = 'updated_at'
        AND table_schema NOT IN ('pg_catalog', 'information_schema')
    LOOP
        EXECUTE format('
            DROP TRIGGER IF EXISTS set_updated_at_trigger ON %I.%I;
            CREATE TRIGGER set_updated_at_trigger
            AFTER INSERT OR UPDATE
            ON %I.%I
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at_now();
        ', r.table_schema, r.table_name, r.table_schema, r.table_name);
    END LOOP;
END $$;

COMMIT;
-- Completed on 2024-12-18 14:16:34

--
-- PostgreSQL database dump complete
--

