CREATE TABLE public.driver_location_history (
    id integer primary key generated by default as identity,
    driver_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    accuracy numeric(8, 2) NOT NULL, -- accuracy in meters from GPS device
    speed numeric(6, 2), -- speed in m/s from GPS device
    heading numeric(5, 2), -- heading in degrees (0-360) from GPS device
    timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivery_id integer REFERENCES deliveries(id) ON DELETE SET NULL
);

CREATE INDEX idx_driver_location_history_driver_id_timestamp ON public.driver_location_history (driver_id, timestamp);
CREATE INDEX idx_driver_location_history_delivery_id ON public.driver_location_history (delivery_id);
CREATE INDEX idx_driver_location_history_timestamp ON public.driver_location_history (timestamp);
